import { Agent } from "@/lib/types";

export const AGENTS: Agent[] = [
  { name: "Astra", src: "/agents/astra/astra.png", role: "Controller" },
  { name: "Breach", src: "/agents/breach/breach.png", role: "Initiator" },
  {
    name: "Brimstone",
    src: "/agents/brimstone/brimstone.png",
    role: "Controller",
  },
  { name: "Chamber", src: "/agents/chamber/chamber.png", role: "Sentinel" },
  { name: "Clove", src: "/agents/clove/clove.png", role: "Controller" },
  { name: "Cypher", src: "/agents/cypher/cypher.png", role: "Sentinel" },
  { name: "Deadlock", src: "/agents/deadlock/deadlock.png", role: "Sentinel" },
  { name: "Fade", src: "/agents/fade/fade.png", role: "Initiator" },
  { name: "Gekko", src: "/agents/gekko/gekko.png", role: "Initiator" },
  { name: "Harbor", src: "/agents/harbor/harbor.png", role: "Controller" },
  { name: "Iso", src: "/agents/iso/iso.png", role: "Duelist" },
  { name: "Jett", src: "/agents/jett/jett.png", role: "Duelist" },
  { name: "KAY/O", src: "/agents/kayo/kayo.png", role: "Initiator" },
  { name: "Killjoy", src: "/agents/killjoy/killjoy.png", role: "Sentinel" },
  { name: "Neon", src: "/agents/neon/neon.png", role: "Duelist" },
  { name: "Omen", src: "/agents/omen/omen.png", role: "Controller" },
  { name: "Phoenix", src: "/agents/phoenix/phoenix.png", role: "Duelist" },
  { name: "Raze", src: "/agents/raze/raze.png", role: "Duelist" },
  { name: "Reyna", src: "/agents/reyna/reyna.png", role: "Duelist" },
  { name: "Sage", src: "/agents/sage/sage.png", role: "Sentinel" },
  { name: "Skye", src: "/agents/skye/skye.png", role: "Initiator" },
  { name: "Sova", src: "/agents/sova/sova.png", role: "Initiator" },
  { name: "Tejo", src: "/agents/tejo/tejo.png", role: "Initiator" },
  { name: "Veto", src: "/agents/veto/veto.png", role: "Sentinel" },
  { name: "Viper", src: "/agents/viper/viper.png", role: "Controller" },
  { name: "Vyse", src: "/agents/vyse/vyse.png", role: "Sentinel" },
  { name: "Waylay", src: "/agents/waylay/waylay.png", role: "Duelist" },
  { name: "Yoru", src: "/agents/yoru/yoru.png", role: "Duelist" },
];
