import { Agent, AgentIconConfig } from "./types";

export const AGENTS: Agent[] = [
  { name: "Astra", src: "/agents/astra/astra.png", role: "Controller" },
  { name: "Breach", src: "/agents/breach/breach.png", role: "Initiator" },
  {
    name: "Brimstone",
    src: "/agents/brimstone/brimstone.png",
    role: "Controller",
  },
  { name: "Chamber", src: "/agents/chamber/chamber.png", role: "Sentinel" },
  { name: "Clove", src: "/agents/clove/clove.png", role: "Controller" },
  { name: "Cypher", src: "/agents/cypher/cypher.png", role: "Sentinel" },
  { name: "Deadlock", src: "/agents/deadlock/deadlock.png", role: "Sentinel" },
  { name: "Fade", src: "/agents/fade/fade.png", role: "Initiator" },
  { name: "Gekko", src: "/agents/gekko/gekko.png", role: "Initiator" },
  { name: "Harbor", src: "/agents/harbor/harbor.png", role: "Controller" },
  { name: "Iso", src: "/agents/iso/iso.png", role: "Duelist" },
  { name: "Jett", src: "/agents/jett/jett.png", role: "Duelist" },
  { name: "KAY/O", src: "/agents/kayo/kayo.png", role: "Initiator" },
  { name: "Killjoy", src: "/agents/killjoy/killjoy.png", role: "Sentinel" },
  { name: "Neon", src: "/agents/neon/neon.png", role: "Duelist" },
  { name: "Omen", src: "/agents/omen/omen.png", role: "Controller" },
  { name: "Phoenix", src: "/agents/phoenix/phoenix.png", role: "Duelist" },
  { name: "Raze", src: "/agents/raze/raze.png", role: "Duelist" },
  { name: "Reyna", src: "/agents/reyna/reyna.png", role: "Duelist" },
  { name: "Sage", src: "/agents/sage/sage.png", role: "Sentinel" },
  { name: "Skye", src: "/agents/skye/skye.png", role: "Initiator" },
  { name: "Sova", src: "/agents/sova/sova.png", role: "Initiator" },
  { name: "Tejo", src: "/agents/tejo/tejo.png", role: "Initiator" },
  { name: "Viper", src: "/agents/viper/viper.png", role: "Controller" },
  { name: "Vyse", src: "/agents/vyse/vyse.png", role: "Sentinel" },
  { name: "Waylay", src: "/agents/waylay/waylay.png", role: "Duelist" },
  { name: "Yoru", src: "/agents/yoru/yoru.png", role: "Duelist" },
];

export const ROLE_ICONS: Record<string, string> = {
  Controller: "/roles/controller.png",
  Duelist: "/roles/duelist.png",
  Initiator: "/roles/initiator.png",
  Sentinel: "/roles/sentinel.png",
};

export const AGENT_ICON_CONFIGS: Record<string, AgentIconConfig> = {
  Astra: [
    {
      id: "nova_pulse",
      icon: "/agents/astra/nova_pulse.png",
      label: "Nova Pulse",
      action: "",
    },
    {
      id: "gravity_well",
      icon: "/agents/astra/gravity_well.png",
      label: "Gravity Well",
      action: "",
    },
    {
      id: "nebula__dissipate",
      icon: "/agents/astra/nebula___dissipate.png",
      label: "Nebula / Dissipate",
      action: "smoke",
    },
    {
      id: "cosmic_divide",
      icon: "/agents/astra/cosmic_divide.png",
      label: "Cosmic Divide",
      action: "ultimate",
    },
    {
      id: "astra_passive",
      icon: "/agents/astra/astral_form.png",
      label: "Astral Star",
      action: "",
    },
  ],
  Breach: [
    {
      id: "aftershock",
      icon: "/agents/breach/aftershock.png",
      label: "Aftershock",
      action: "",
    },
    {
      id: "fault_line",
      icon: "/agents/breach/fault_line.png",
      label: "Fault Line",
      action: "",
    },
    {
      id: "flashpoint",
      icon: "/agents/breach/flashpoint.png",
      label: "Flashpoint",
      action: "",
    },
    {
      id: "rolling_thunder",
      icon: "/agents/breach/rolling_thunder.png",
      label: "Rolling Thunder",
      action: "ultimate",
    },
  ],
  Brimstone: [
    {
      id: "incendiary",
      icon: "/agents/brimstone/incendiary.png",
      label: "Incendiary",
      action: "",
    },
    {
      id: "sky_smoke",
      icon: "/agents/brimstone/sky_smoke.png",
      label: "Sky Smoke",
      action: "",
    },
    {
      id: "stim_beacon",
      icon: "/agents/brimstone/stim_beacon.png",
      label: "Stim Beacon",
      action: "",
    },
    {
      id: "orbital_strike",
      icon: "/agents/brimstone/orbital_strike.png",
      label: "Orbital Strike",
      action: "ultimate",
    },
  ],
  Chamber: [
    {
      id: "headhunter",
      icon: "/agents/chamber/headhunter.png",
      label: "Headhunter",
      action: "",
    },
    {
      id: "rendezvous",
      icon: "/agents/chamber/rendezvous.png",
      label: "Rendezvous",
      action: "",
    },
    {
      id: "trademark",
      icon: "/agents/chamber/trademark.png",
      label: "Trademark",
      action: "",
    },
    {
      id: "tour_de_force",
      icon: "/agents/chamber/tour_de_force.png",
      label: "Tour de Force",
      action: "ultimate",
    },
  ],
  Clove: [
    {
      id: "meddle",
      icon: "/agents/clove/meddle.png",
      label: "Meddle",
      action: "",
    },
    {
      id: "not_dead_yet",
      icon: "/agents/clove/not_dead_yet.png",
      label: "Not Dead Yet",
      action: "ultimate",
    },
    {
      id: "pick_me_up",
      icon: "/agents/clove/pick_me_up.png",
      label: "Pick Me Up",
      action: "",
    },
    {
      id: "ruse",
      icon: "/agents/clove/ruse.png",
      label: "Ruse",
      action: "",
    },
  ],
  Cypher: [
    {
      id: "cyber_cage",
      icon: "/agents/cypher/cyber_cage.png",
      label: "Cyber Cage",
      action: "",
    },
    {
      id: "spycam",
      icon: "/agents/cypher/spycam.png",
      label: "Spycam",
      action: "",
    },
    {
      id: "trapwire",
      icon: "/agents/cypher/trapwire.png",
      label: "Trapwire",
      action: "",
    },
    {
      id: "neural_theft",
      icon: "/agents/cypher/neural_theft.png",
      label: "Neural Theft",
      action: "ultimate",
    },
  ],
  Deadlock: [
    {
      id: "barrier_mesh",
      icon: "/agents/deadlock/barrier_mesh.png",
      label: "Barrier Mesh",
      action: "",
    },
    {
      id: "gravnet",
      icon: "/agents/deadlock/gravnet.png",
      label: "GravNet",
      action: "",
    },
    {
      id: "sonic_sensor",
      icon: "/agents/deadlock/sonic_sensor.png",
      label: "Sonic Sensor",
      action: "",
    },
    {
      id: "annihilation",
      icon: "/agents/deadlock/annihilation.png",
      label: "Annihilation",
      action: "ultimate",
    },
  ],
  Fade: [
    {
      id: "prowler",
      icon: "/agents/fade/prowler.png",
      label: "Prowler",
      action: "",
    },
    {
      id: "seize",
      icon: "/agents/fade/seize.png",
      label: "Seize",
      action: "",
    },
    {
      id: "haunt",
      icon: "/agents/fade/haunt.png",
      label: "Haunt",
      action: "",
    },
    {
      id: "nightfall",
      icon: "/agents/fade/nightfall.png",
      label: "Nightfall",
      action: "ultimate",
    },
  ],
  Gekko: [
    {
      id: "wingman",
      icon: "/agents/gekko/wingman.png",
      label: "Wingman",
      action: "",
    },
    {
      id: "dizzy",
      icon: "/agents/gekko/dizzy.png",
      label: "Dizzy",
      action: "",
    },
    {
      id: "mosh_pit",
      icon: "/agents/gekko/mosh_pit.png",
      label: "Mosh Pit",
      action: "",
    },
    {
      id: "thrash",
      icon: "/agents/gekko/thrash.png",
      label: "Thrash",
      action: "ultimate",
    },
  ],
  Harbor: [
    {
      id: "cascade",
      icon: "/agents/harbor/cascade.png",
      label: "Cascade",
      action: "",
    },
    {
      id: "cove",
      icon: "/agents/harbor/cove.png",
      label: "Cove",
      action: "",
    },
    {
      id: "high_tide",
      icon: "/agents/harbor/high_tide.png",
      label: "High Tide",
      action: "",
    },
    {
      id: "reckoning",
      icon: "/agents/harbor/reckoning.png",
      label: "Reckoning",
      action: "ultimate",
    },
  ],
  Iso: [
    {
      id: "undercut",
      icon: "/agents/iso/undercut.png",
      label: "Undercut",
      action: "",
    },
    {
      id: "double_tap",
      icon: "/agents/iso/double_tap.png",
      label: "Double Tap",
      action: "",
    },
    {
      id: "contingency",
      icon: "/agents/iso/contingency.png",
      label: "Contingency",
      action: "",
    },
    {
      id: "kill_contract",
      icon: "/agents/iso/kill_contract.png",
      label: "Kill Contract",
      action: "ultimate",
    },
  ],
  Jett: [
    {
      id: "updraft",
      icon: "/agents/jett/updraft.png",
      label: "Updraft",
      action: "",
    },
    {
      id: "tailwind",
      icon: "/agents/jett/tailwind.png",
      label: "Tailwind",
      action: "",
    },
    {
      id: "cloudburst",
      icon: "/agents/jett/cloudburst.png",
      label: "Cloudburst",
      action: "",
    },
    {
      id: "blade_storm",
      icon: "/agents/jett/blade_storm.png",
      label: "Blade Storm",
      action: "ultimate",
    },
  ],
  "KAY/O": [
    {
      id: "fragment",
      icon: "/agents/kayo/fragment.png",
      label: "Fragment",
      action: "",
    },
    {
      id: "flashdrive",
      icon: "/agents/kayo/flashdrive.png",
      label: "Flash/Drive",
      action: "",
    },
    {
      id: "zeropoint",
      icon: "/agents/kayo/zeropoint.png",
      label: "Zero/Point",
      action: "",
    },
    {
      id: "nullcmd",
      icon: "/agents/kayo/nullcmd.png",
      label: "NULL/cmd",
      action: "ultimate",
    },
  ],
  Killjoy: [
    {
      id: "alarmbot",
      icon: "/agents/killjoy/alarmbot.png",
      label: "Alarmbot",
      action: "",
    },
    {
      id: "turret",
      icon: "/agents/killjoy/turret.png",
      label: "Turret",
      action: "",
    },
    {
      id: "nanoswarm",
      icon: "/agents/killjoy/nanoswarm.png",
      label: "Nanoswarm",
      action: "",
    },
    {
      id: "lockdown",
      icon: "/agents/killjoy/lockdown.png",
      label: "Lockdown",
      action: "ultimate",
    },
  ],
  Neon: [
    {
      id: "relay_bolt",
      icon: "/agents/neon/relay_bolt.png",
      label: "Relay Bolt",
      action: "",
    },
    {
      id: "high_gear",
      icon: "/agents/neon/high_gear.png",
      label: "High Gear",
      action: "",
    },
    {
      id: "fast_lane",
      icon: "/agents/neon/fast_lane.png",
      label: "Fast Lane",
      action: "",
    },
    {
      id: "overdrive",
      icon: "/agents/neon/overdrive.png",
      label: "Overdrive",
      action: "ultimate",
    },
  ],
  Omen: [
    {
      id: "paranoia",
      icon: "/agents/omen/paranoia.png",
      label: "Paranoia",
      action: "",
    },
    {
      id: "dark_cover",
      icon: "/agents/omen/dark_cover.png",
      label: "Dark Cover",
      action: "",
    },
    {
      id: "shrouded_step",
      icon: "/agents/omen/shrouded_step.png",
      label: "Shrouded Step",
      action: "",
    },
    {
      id: "from_the_shadows",
      icon: "/agents/omen/from_the_shadows.png",
      label: "From the Shadows",
      action: "ultimate",
    },
  ],
  Phoenix: [
    {
      id: "curveball",
      icon: "/agents/phoenix/curveball.png",
      label: "Curveball",
      action: "",
    },
    {
      id: "hot_hands",
      icon: "/agents/phoenix/hot_hands.png",
      label: "Hot Hands",
      action: "",
    },
    {
      id: "blaze",
      icon: "/agents/phoenix/blaze.png",
      label: "Blaze",
      action: "",
    },
    {
      id: "run_it_back",
      icon: "/agents/phoenix/run_it_back.png",
      label: "Run it Back",
      action: "ultimate",
    },
  ],
  Raze: [
    {
      id: "blast_pack",
      icon: "/agents/raze/blast_pack.png",
      label: "Blast Pack",
      action: "",
    },
    {
      id: "paint_shells",
      icon: "/agents/raze/paint_shells.png",
      label: "Paint Shells",
      action: "",
    },
    {
      id: "boom_bot",
      icon: "/agents/raze/boom_bot.png",
      label: "Boom Bot",
      action: "",
    },
    {
      id: "showstopper",
      icon: "/agents/raze/showstopper.png",
      label: "Showstopper",
      action: "ultimate",
    },
  ],
  Reyna: [
    {
      id: "devour",
      icon: "/agents/reyna/devour.png",
      label: "Devour",
      action: "",
    },
    {
      id: "dismiss",
      icon: "/agents/reyna/dismiss.png",
      label: "Dismiss",
      action: "",
    },
    {
      id: "leer",
      icon: "/agents/reyna/leer.png",
      label: "Leer",
      action: "",
    },
    {
      id: "empress",
      icon: "/agents/reyna/empress.png",
      label: "Empress",
      action: "ultimate",
    },
  ],
  Sage: [
    {
      id: "slow_orb",
      icon: "/agents/sage/slow_orb.png",
      label: "Slow Orb",
      action: "",
    },
    {
      id: "healing_orb",
      icon: "/agents/sage/healing_orb.png",
      label: "Healing Orb",
      action: "",
    },
    {
      id: "barrier_orb",
      icon: "/agents/sage/barrier_orb.png",
      label: "Barrier Orb",
      action: "",
    },
    {
      id: "resurrection",
      icon: "/agents/sage/resurrection.png",
      label: "Resurrection",
      action: "ultimate",
    },
  ],
  Skye: [
    {
      id: "trailblazer",
      icon: "/agents/skye/trailblazer.png",
      label: "Trailblazer",
      action: "",
    },
    {
      id: "guiding_light",
      icon: "/agents/skye/guiding_light.png",
      label: "Guiding Light",
      action: "",
    },
    {
      id: "regrowth",
      icon: "/agents/skye/regrowth.png",
      label: "Regrowth",
      action: "",
    },
    {
      id: "seekers",
      icon: "/agents/skye/seekers.png",
      label: "Seekers",
      action: "ultimate",
    },
  ],
  Sova: [
    {
      id: "shock_bolt",
      icon: "/agents/sova/shock_bolt.png",
      label: "Shock Bolt",
      action: "",
    },
    {
      id: "recon_bolt",
      icon: "/agents/sova/recon_bolt.png",
      label: "Recon Bolt",
      action: "",
    },
    {
      id: "owl_drone",
      icon: "/agents/sova/owl_drone.png",
      label: "Owl Drone",
      action: "",
    },
    {
      id: "hunters_fury",
      icon: "/agents/sova/hunter's_fury.png",
      label: "Hunter's Fury",
      action: "ultimate",
    },
  ],
  Tejo: [
    {
      id: "stealth_drone",
      icon: "/agents/tejo/stealth_drone.png",
      label: "Stealth Drone",
      action: "",
    },
    {
      id: "guided_salvo",
      icon: "/agents/tejo/guided_salvo.png",
      label: "Guided Salvo",
      action: "",
    },
    {
      id: "special_delivery",
      icon: "/agents/tejo/special_delivery.png",
      label: "Special Delivery",
      action: "",
    },
    {
      id: "armageddon",
      icon: "/agents/tejo/armageddon.png",
      label: "Armageddon",
      action: "ultimate",
    },
  ],
  Viper: [
    {
      id: "poison_cloud",
      icon: "/agents/viper/poison_cloud.png",
      label: "Poison Cloud",
      action: "",
    },
    {
      id: "toxic_screen",
      icon: "/agents/viper/toxic_screen.png",
      label: "Toxic Screen",
      action: "",
    },
    {
      id: "snake_bite",
      icon: "/agents/viper/snake_bite.png",
      label: "Snake Bite",
      action: "",
    },
    {
      id: "vipers_pit",
      icon: "/agents/viper/viper's_pit.png",
      label: "Viper's Pit",
      action: "ultimate",
    },
  ],
  Vyse: [
    {
      id: "arc_rose",
      icon: "/agents/vyse/arc_rose.png",
      label: "Arc Rose",
      action: "",
    },
    {
      id: "razorvine",
      icon: "/agents/vyse/razorvine.png",
      label: "Razor Vine",
      action: "",
    },
    {
      id: "shear",
      icon: "/agents/vyse/shear.png",
      label: "Shear",
      action: "",
    },
    {
      id: "steel_garden",
      icon: "/agents/vyse/steel_garden.png",
      label: "Steel Garden",
      action: "ultimate",
    },
  ],
  Waylay: [
    {
      id: "saturate",
      icon: "/agents/waylay/saturate.png",
      label: "Saturate",
      action: "",
    },
    {
      id: "refract",
      icon: "/agents/waylay/refract.png",
      label: "Refract",
      action: "",
    },
    {
      id: "lightspeed",
      icon: "/agents/waylay/lightspeed.png",
      label: "Lightspeed",
      action: "",
    },
    {
      id: "convergent_paths",
      icon: "/agents/waylay/convergent_paths.png",
      label: "Convergent Paths",
      action: "ultimate",
    },
  ],
  Yoru: [
    {
      id: "fakeout",
      icon: "/agents/yoru/fakeout.png",
      label: "Fakeout",
      action: "",
    },
    {
      id: "gatecrash",
      icon: "/agents/yoru/gatecrash.png",
      label: "Gatecrash",
      action: "",
    },
    {
      id: "blindside",
      icon: "/agents/yoru/blindside.png",
      label: "Blindside",
      action: "",
    },
    {
      id: "dimensional_drift",
      icon: "/agents/yoru/dimensional_drift.png",
      label: "Dimensional Drift",
      action: "ultimate",
    },
  ],
};
